run:
	cp ../vcseedftp ./vcseedftp.py
	( which python  && python --version  && python ./string_test.py ) || true
	( which python2 && python2 --version && python2 ./string_test.py ) || true
	( which python3 && python3 --version && python3 ./string_test.py ) || true
	rm ./vcseedftp.py *.pyc
