#!/usr/bin/env python
#encoding: utf8
#
# Copyright: Chun-Yu Lee (Mat) <matlinuxer2@gmail.com> || Dieter Hsu <dieterplex@gmail.com>
#

import os
import vcseedftp

vcseedftp.LCD = os.path.dirname( __file__ )

sample_output = [ 
"""
M	.gitignore
A	.htaccess
D	Classes/MailCreateOrder.class1020.php
M	Classes/function.php
M	Classes/orderClass.php
D	Config/Email.txt
D	Config/cache/Forumclass_show.php
D	Config/cache/Groupclass_show.php
D	Config/cache/Newsclass_show.php
D	Config/cache/ProductclassIndex_show.php
D	Config/cache/Productclass_show.php
D	Config/cache/RegisterMap.day.inc
D	Config/cache/RegisterMap.month.inc
D	Config/cache/SaleMap.day.inc
D	Config/cache/SaleMap.month.inc
D	Config/cache/count.php
D	Config/cache/countNum.php
D	Config/cache/setwatermark.php
D	Config/cache/upIndexClass.php
D	Config/conf.global.php
M	Resources/FCKeditor/editor/dialog/fck_template.html
M	Resources/FCKeditor/editor/lang/eu.js
A	Resources/ckeditor/.htaccess
A	Resources/ckeditor/CHANGES.html
A	Resources/ckeditor/INSTALL.html
A	Resources/ckeditor/LICENSE.html
A	Resources/ckeditor/_samples/adobeair/application.xml
A	Resources/ckeditor/_samples/adobeair/run.bat
A	Resources/ckeditor/_samples/adobeair/run.sh
A	Resources/ckeditor/_samples/adobeair/sample.html
A	Resources/ckeditor/_samples/ajax.html
A	Resources/ckeditor/_samples/api.html
A	Resources/ckeditor/_samples/api_dialog.html
A	Resources/ckeditor/_samples/api_dialog/my_dialog.js
A	Resources/ckeditor/_samples/asp/advanced.asp
A	Resources/ckeditor/_samples/asp/events.asp
A	Resources/ckeditor/_samples/asp/index.html
A	Resources/ckeditor/_samples/asp/replace.asp
A	Resources/ckeditor/_samples/asp/replaceall.asp
A	Resources/ckeditor/_samples/asp/sample_posteddata.asp
A	Resources/ckeditor/_samples/asp/standalone.asp
A	Resources/ckeditor/_samples/assets/_posteddata.php
A	Resources/ckeditor/_samples/assets/output_for_flash.fla
A	Resources/ckeditor/_samples/assets/output_for_flash.swf
A	Resources/ckeditor/_samples/assets/output_xhtml.css
A	Resources/ckeditor/_samples/assets/parsesample.css
A	Resources/ckeditor/_samples/assets/swfobject.js
A	Resources/ckeditor/_samples/autogrow.html
A	Resources/ckeditor/_samples/bbcode.html
A	Resources/ckeditor/_samples/devtools.html
A	Resources/ckeditor/_samples/divreplace.html
A	Resources/ckeditor/_samples/enterkey.html
A	Resources/ckeditor/_samples/fullpage.html
A	Resources/ckeditor/_samples/index.html
A	Resources/ckeditor/_samples/jqueryadapter.html
A	Resources/ckeditor/_samples/output_for_flash.html
A	Resources/ckeditor/_samples/output_html.html
A	Resources/ckeditor/_samples/output_xhtml.html
A	Resources/ckeditor/_samples/php/advanced.php
A	Resources/ckeditor/_samples/php/events.php
A	Resources/ckeditor/_samples/php/index.html
A	Resources/ckeditor/_samples/php/replace.php
A	Resources/ckeditor/_samples/php/replaceall.php
A	Resources/ckeditor/_samples/php/standalone.php
A	Resources/ckeditor/_samples/placeholder.html
A	Resources/ckeditor/_samples/readonly.html
A	Resources/ckeditor/_samples/replacebyclass.html
A	Resources/ckeditor/_samples/replacebycode.html
A	Resources/ckeditor/_samples/sample.css
A	Resources/ckeditor/_samples/sample.js
A	Resources/ckeditor/_samples/sample_posteddata.php
A	Resources/ckeditor/_samples/sharedspaces.html
A	Resources/ckeditor/_samples/skins.html
A	Resources/ckeditor/_samples/stylesheetparser.html
A	Resources/ckeditor/_samples/tableresize.html
A	Resources/ckeditor/_samples/ui_color.html
A	Resources/ckeditor/_samples/ui_languages.html
A	Resources/ckeditor/_source/adapters/jquery.js
A	Resources/ckeditor/_source/core/_bootstrap.js
A	Resources/ckeditor/_source/core/ckeditor.js
A	Resources/ckeditor/_source/core/ckeditor_base.js
A	Resources/ckeditor/_source/core/ckeditor_basic.js
A	Resources/ckeditor/_source/core/command.js
A	Resources/ckeditor/_source/core/commanddefinition.js
A	Resources/ckeditor/_source/core/config.js
A	Resources/ckeditor/_source/core/dom.js
A	Resources/ckeditor/_source/core/dom/comment.js
A	Resources/ckeditor/_source/core/dom/document.js
A	Resources/ckeditor/_source/core/dom/documentfragment.js
A	Resources/ckeditor/_source/core/dom/domobject.js
A	Resources/ckeditor/_source/core/dom/element.js
A	Resources/ckeditor/_source/core/dom/elementpath.js
A	Resources/ckeditor/_source/core/dom/event.js
A	Resources/ckeditor/_source/core/dom/node.js
A	Resources/ckeditor/_source/core/dom/nodelist.js
A	Resources/ckeditor/_source/core/dom/range.js
A	Resources/ckeditor/_source/core/dom/rangelist.js
A	Resources/ckeditor/_source/core/dom/text.js
A	Resources/ckeditor/_source/core/dom/walker.js
A	Resources/ckeditor/_source/core/dom/window.js
A	Resources/ckeditor/_source/core/dtd.js
A	Resources/ckeditor/_source/core/editor.js
A	Resources/ckeditor/_source/core/editor_basic.js
A	Resources/ckeditor/_source/core/env.js
A	Resources/ckeditor/_source/core/event.js
A	Resources/ckeditor/_source/core/eventInfo.js
A	Resources/ckeditor/_source/core/focusmanager.js
A	Resources/ckeditor/_source/core/htmlparser.js
A	Resources/ckeditor/_source/core/htmlparser/basicwriter.js
A	Resources/ckeditor/_source/core/htmlparser/cdata.js
A	Resources/ckeditor/_source/core/htmlparser/comment.js
A	Resources/ckeditor/_source/core/htmlparser/element.js
A	Resources/ckeditor/_source/core/htmlparser/filter.js
A	Resources/ckeditor/_source/core/htmlparser/fragment.js
A	Resources/ckeditor/_source/core/htmlparser/text.js
A	Resources/ckeditor/_source/core/lang.js
A	Resources/ckeditor/_source/core/loader.js
A	Resources/ckeditor/_source/core/plugindefinition.js
A	Resources/ckeditor/_source/core/plugins.js
A	Resources/ckeditor/_source/core/resourcemanager.js
A	Resources/ckeditor/_source/core/scriptloader.js
A	Resources/ckeditor/_source/core/skins.js
A	Resources/ckeditor/_source/core/themes.js
A	Resources/ckeditor/_source/core/tools.js
A	Resources/ckeditor/_source/core/ui.js
A	Resources/ckeditor/_source/lang/_languages.js
A	Resources/ckeditor/_source/lang/_translationstatus.txt
A	Resources/ckeditor/_source/lang/af.js
A	Resources/ckeditor/_source/lang/ar.js
A	Resources/ckeditor/_source/lang/bg.js
A	Resources/ckeditor/_source/lang/bn.js
A	Resources/ckeditor/_source/lang/bs.js
A	Resources/ckeditor/_source/lang/ca.js
A	Resources/ckeditor/_source/lang/cs.js
A	Resources/ckeditor/_source/lang/cy.js
A	Resources/ckeditor/_source/lang/da.js
A	Resources/ckeditor/_source/lang/de.js
A	Resources/ckeditor/_source/lang/el.js
A	Resources/ckeditor/_source/lang/en-au.js
A	Resources/ckeditor/_source/lang/en-ca.js
A	Resources/ckeditor/_source/lang/en-gb.js
A	Resources/ckeditor/_source/lang/en.js
A	Resources/ckeditor/_source/lang/eo.js
A	Resources/ckeditor/_source/lang/es.js
A	Resources/ckeditor/_source/lang/et.js
A	Resources/ckeditor/_source/lang/eu.js
A	Resources/ckeditor/_source/lang/fa.js
A	Resources/ckeditor/_source/lang/fi.js
A	Resources/ckeditor/_source/lang/fo.js
A	Resources/ckeditor/_source/lang/fr-ca.js
A	Resources/ckeditor/_source/lang/fr.js
A	Resources/ckeditor/_source/lang/gl.js
A	Resources/ckeditor/_source/lang/gu.js
A	Resources/ckeditor/_source/lang/he.js
A	Resources/ckeditor/_source/lang/hi.js
A	Resources/ckeditor/_source/lang/hr.js
A	Resources/ckeditor/_source/lang/hu.js
A	Resources/ckeditor/_source/lang/is.js
A	Resources/ckeditor/_source/lang/it.js
A	Resources/ckeditor/_source/lang/ja.js
A	Resources/ckeditor/_source/lang/km.js
A	Resources/ckeditor/_source/lang/ko.js
A	Resources/ckeditor/_source/lang/lt.js
A	Resources/ckeditor/_source/lang/lv.js
A	Resources/ckeditor/_source/lang/mn.js
A	Resources/ckeditor/_source/lang/ms.js
A	Resources/ckeditor/_source/lang/nb.js
A	Resources/ckeditor/_source/lang/nl.js
A	Resources/ckeditor/_source/lang/no.js
A	Resources/ckeditor/_source/lang/pl.js
A	Resources/ckeditor/_source/lang/pt-br.js
A	Resources/ckeditor/_source/lang/pt.js
A	Resources/ckeditor/_source/lang/ro.js
A	Resources/ckeditor/_source/lang/ru.js
A	Resources/ckeditor/_source/lang/sk.js
A	Resources/ckeditor/_source/lang/sl.js
A	Resources/ckeditor/_source/lang/sr-latn.js
A	Resources/ckeditor/_source/lang/sr.js
A	Resources/ckeditor/_source/lang/sv.js
A	Resources/ckeditor/_source/lang/th.js
A	Resources/ckeditor/_source/lang/tr.js
A	Resources/ckeditor/_source/lang/uk.js
A	Resources/ckeditor/_source/lang/vi.js
A	Resources/ckeditor/_source/lang/zh-cn.js
A	Resources/ckeditor/_source/lang/zh.js
A	Resources/ckeditor/_source/plugins/a11yhelp/dialogs/a11yhelp.js
A	Resources/ckeditor/_source/plugins/a11yhelp/lang/en.js
A	Resources/ckeditor/_source/plugins/a11yhelp/lang/he.js
A	Resources/ckeditor/_source/plugins/a11yhelp/plugin.js
A	Resources/ckeditor/_source/plugins/about/dialogs/about.js
A	Resources/ckeditor/_source/plugins/about/dialogs/logo_ckeditor.png
A	Resources/ckeditor/_source/plugins/about/plugin.js
A	Resources/ckeditor/_source/plugins/adobeair/plugin.js
A	Resources/ckeditor/_source/plugins/ajax/plugin.js
A	Resources/ckeditor/_source/plugins/autogrow/plugin.js
A	Resources/ckeditor/_source/plugins/basicstyles/plugin.js
A	Resources/ckeditor/_source/plugins/bbcode/plugin.js
A	Resources/ckeditor/_source/plugins/bidi/plugin.js
A	Resources/ckeditor/_source/plugins/blockquote/plugin.js
A	Resources/ckeditor/_source/plugins/button/plugin.js
A	Resources/ckeditor/_source/plugins/clipboard/dialogs/paste.js
A	Resources/ckeditor/_source/plugins/clipboard/plugin.js
A	Resources/ckeditor/_source/plugins/colorbutton/plugin.js
A	Resources/ckeditor/_source/plugins/colordialog/dialogs/colordialog.js
A	Resources/ckeditor/_source/plugins/colordialog/plugin.js
A	Resources/ckeditor/_source/plugins/contextmenu/plugin.js
A	Resources/ckeditor/_source/plugins/devtools/lang/en.js
A	Resources/ckeditor/_source/plugins/devtools/plugin.js
A	Resources/ckeditor/_source/plugins/dialog/dialogDefinition.js
A	Resources/ckeditor/_source/plugins/dialog/plugin.js
A	Resources/ckeditor/_source/plugins/dialogadvtab/plugin.js
A	Resources/ckeditor/_source/plugins/dialogui/plugin.js
A	Resources/ckeditor/_source/plugins/div/dialogs/div.js
A	Resources/ckeditor/_source/plugins/div/plugin.js
A	Resources/ckeditor/_source/plugins/docprops/dialogs/docprops.js
A	Resources/ckeditor/_source/plugins/docprops/plugin.js
A	Resources/ckeditor/_source/plugins/domiterator/plugin.js
A	Resources/ckeditor/_source/plugins/editingblock/plugin.js
A	Resources/ckeditor/_source/plugins/elementspath/plugin.js
A	Resources/ckeditor/_source/plugins/enterkey/plugin.js
A	Resources/ckeditor/_source/plugins/entities/plugin.js
A	Resources/ckeditor/_source/plugins/fakeobjects/plugin.js
A	Resources/ckeditor/_source/plugins/filebrowser/plugin.js
A	Resources/ckeditor/_source/plugins/find/dialogs/find.js
A	Resources/ckeditor/_source/plugins/find/plugin.js
A	Resources/ckeditor/_source/plugins/flash/dialogs/flash.js
A	Resources/ckeditor/_source/plugins/flash/plugin.js
A	Resources/ckeditor/_source/plugins/floatpanel/plugin.js
A	Resources/ckeditor/_source/plugins/font/plugin.js
A	Resources/ckeditor/_source/plugins/format/plugin.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/button.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/checkbox.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/form.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/hiddenfield.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/radio.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/select.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/textarea.js
A	Resources/ckeditor/_source/plugins/forms/dialogs/textfield.js
A	Resources/ckeditor/_source/plugins/forms/images/hiddenfield.gif
A	Resources/ckeditor/_source/plugins/forms/plugin.js
A	Resources/ckeditor/_source/plugins/horizontalrule/plugin.js
A	Resources/ckeditor/_source/plugins/htmldataprocessor/plugin.js
A	Resources/ckeditor/_source/plugins/htmlwriter/plugin.js
A	Resources/ckeditor/_source/plugins/iframe/dialogs/iframe.js
A	Resources/ckeditor/_source/plugins/iframe/images/placeholder.png
A	Resources/ckeditor/_source/plugins/iframe/plugin.js
A	Resources/ckeditor/_source/plugins/iframedialog/plugin.js
A	Resources/ckeditor/_source/plugins/image/dialogs/image.js
A	Resources/ckeditor/_source/plugins/image/plugin.js
A	Resources/ckeditor/_source/plugins/indent/plugin.js
A	Resources/ckeditor/_source/plugins/justify/plugin.js
A	Resources/ckeditor/_source/plugins/keystrokes/plugin.js
A	Resources/ckeditor/_source/plugins/link/dialogs/anchor.js
A	Resources/ckeditor/_source/plugins/link/dialogs/link.js
A	Resources/ckeditor/_source/plugins/link/images/anchor.gif
A	Resources/ckeditor/_source/plugins/link/plugin.js
A	Resources/ckeditor/_source/plugins/list/plugin.js
A	Resources/ckeditor/_source/plugins/listblock/plugin.js
A	Resources/ckeditor/_source/plugins/liststyle/dialogs/liststyle.js
A	Resources/ckeditor/_source/plugins/liststyle/plugin.js
A	Resources/ckeditor/_source/plugins/maximize/plugin.js
A	Resources/ckeditor/_source/plugins/menu/plugin.js
A	Resources/ckeditor/_source/plugins/menubutton/plugin.js
A	Resources/ckeditor/_source/plugins/newpage/plugin.js
A	Resources/ckeditor/_source/plugins/pagebreak/images/pagebreak.gif
A	Resources/ckeditor/_source/plugins/pagebreak/plugin.js
A	Resources/ckeditor/_source/plugins/panel/plugin.js
A	Resources/ckeditor/_source/plugins/panelbutton/plugin.js
A	Resources/ckeditor/_source/plugins/pastefromword/filter/default.js
A	Resources/ckeditor/_source/plugins/pastefromword/plugin.js
A	Resources/ckeditor/_source/plugins/pastetext/dialogs/pastetext.js
A	Resources/ckeditor/_source/plugins/pastetext/plugin.js
A	Resources/ckeditor/_source/plugins/placeholder/dialogs/placeholder.js
A	Resources/ckeditor/_source/plugins/placeholder/lang/en.js
A	Resources/ckeditor/_source/plugins/placeholder/lang/he.js
A	Resources/ckeditor/_source/plugins/placeholder/placeholder.gif
A	Resources/ckeditor/_source/plugins/placeholder/plugin.js
A	Resources/ckeditor/_source/plugins/popup/plugin.js
A	Resources/ckeditor/_source/plugins/preview/plugin.js
A	Resources/ckeditor/_source/plugins/print/plugin.js
A	Resources/ckeditor/_source/plugins/removeformat/plugin.js
A	Resources/ckeditor/_source/plugins/resize/plugin.js
A	Resources/ckeditor/_source/plugins/richcombo/plugin.js
A	Resources/ckeditor/_source/plugins/save/plugin.js
A	Resources/ckeditor/_source/plugins/scayt/dialogs/options.js
A	Resources/ckeditor/_source/plugins/scayt/dialogs/toolbar.css
A	Resources/ckeditor/_source/plugins/selection/plugin.js
A	Resources/ckeditor/_source/plugins/showblocks/images/block_address.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_blockquote.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_div.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_h1.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_h2.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_h3.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_h4.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_h5.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_h6.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_p.png
A	Resources/ckeditor/_source/plugins/showblocks/images/block_pre.png
A	Resources/ckeditor/_source/plugins/showblocks/plugin.js
A	Resources/ckeditor/_source/plugins/showborders/plugin.js
A	Resources/ckeditor/_source/plugins/smiley/dialogs/smiley.js
A	Resources/ckeditor/_source/plugins/smiley/images/angel_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/angry_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/broken_heart.gif
A	Resources/ckeditor/_source/plugins/smiley/images/confused_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/cry_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/devil_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/embaressed_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/envelope.gif
A	Resources/ckeditor/_source/plugins/smiley/images/heart.gif
A	Resources/ckeditor/_source/plugins/smiley/images/kiss.gif
A	Resources/ckeditor/_source/plugins/smiley/images/lightbulb.gif
A	Resources/ckeditor/_source/plugins/smiley/images/omg_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/regular_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/sad_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/shades_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/teeth_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/thumbs_down.gif
A	Resources/ckeditor/_source/plugins/smiley/images/thumbs_up.gif
A	Resources/ckeditor/_source/plugins/smiley/images/tounge_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/whatchutalkingabout_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/images/wink_smile.gif
A	Resources/ckeditor/_source/plugins/smiley/plugin.js
A	Resources/ckeditor/_source/plugins/sourcearea/plugin.js
A	Resources/ckeditor/_source/plugins/specialchar/dialogs/specialchar.js
A	Resources/ckeditor/_source/plugins/specialchar/lang/en.js
A	Resources/ckeditor/_source/plugins/specialchar/plugin.js
A	Resources/ckeditor/_source/plugins/styles/plugin.js
A	Resources/ckeditor/_source/plugins/styles/styles/default.js
A	Resources/ckeditor/_source/plugins/stylescombo/plugin.js
A	Resources/ckeditor/_source/plugins/stylesheetparser/plugin.js
A	Resources/ckeditor/_source/plugins/tab/plugin.js
A	Resources/ckeditor/_source/plugins/table/dialogs/table.js
A	Resources/ckeditor/_source/plugins/table/plugin.js
A	Resources/ckeditor/_source/plugins/tableresize/plugin.js
A	Resources/ckeditor/_source/plugins/tabletools/dialogs/tableCell.js
A	Resources/ckeditor/_source/plugins/tabletools/plugin.js
A	Resources/ckeditor/_source/plugins/templates/dialogs/templates.js
A	Resources/ckeditor/_source/plugins/templates/plugin.js
A	Resources/ckeditor/_source/plugins/templates/templates/default.js
A	Resources/ckeditor/_source/plugins/templates/templates/images/template2.gif
A	Resources/ckeditor/_source/plugins/templates/templates/images/template3.gif
A	Resources/ckeditor/_source/plugins/toolbar/plugin.js
A	Resources/ckeditor/_source/plugins/uicolor/dialogs/uicolor.js
A	Resources/ckeditor/_source/plugins/uicolor/lang/en.js
A	Resources/ckeditor/_source/plugins/uicolor/lang/he.js
A	Resources/ckeditor/_source/plugins/uicolor/plugin.js
A	Resources/ckeditor/_source/plugins/uicolor/uicolor.gif
A	Resources/ckeditor/_source/plugins/uicolor/yui/assets/hue_bg.png
A	Resources/ckeditor/_source/plugins/uicolor/yui/assets/hue_thumb.png
A	Resources/ckeditor/_source/plugins/uicolor/yui/assets/picker_mask.png
A	Resources/ckeditor/_source/plugins/uicolor/yui/assets/picker_thumb.png
A	Resources/ckeditor/_source/plugins/uicolor/yui/assets/yui.css
A	Resources/ckeditor/_source/plugins/uicolor/yui/yui.js
A	Resources/ckeditor/_source/plugins/undo/plugin.js
A	Resources/ckeditor/_source/plugins/wsc/dialogs/ciframe.html
A	Resources/ckeditor/_source/plugins/wsc/dialogs/tmpFrameset.html
A	Resources/ckeditor/_source/plugins/wsc/dialogs/wsc.css
A	Resources/ckeditor/_source/plugins/wsc/dialogs/wsc.js
A	Resources/ckeditor/_source/plugins/wsc/plugin.js
A	Resources/ckeditor/_source/plugins/wysiwygarea/plugin.js
A	Resources/ckeditor/_source/plugins/xml/plugin.js
A	Resources/ckeditor/_source/skins/kama/dialog.css
A	Resources/ckeditor/_source/skins/kama/editor.css
A	Resources/ckeditor/_source/skins/kama/elementspath.css
A	Resources/ckeditor/_source/skins/kama/icons.css
A	Resources/ckeditor/_source/skins/kama/icons.png
A	Resources/ckeditor/_source/skins/kama/icons_rtl.png
A	Resources/ckeditor/_source/skins/kama/images/dialog_sides.gif
A	Resources/ckeditor/_source/skins/kama/images/dialog_sides.png
A	Resources/ckeditor/_source/skins/kama/images/dialog_sides_rtl.png
A	Resources/ckeditor/_source/skins/kama/images/mini.gif
A	Resources/ckeditor/_source/skins/kama/images/noimage.png
A	Resources/ckeditor/_source/skins/kama/images/sprites.png
A	Resources/ckeditor/_source/skins/kama/images/sprites_ie6.png
A	Resources/ckeditor/_source/skins/kama/images/toolbar_start.gif
A	Resources/ckeditor/_source/skins/kama/mainui.css
A	Resources/ckeditor/_source/skins/kama/menu.css
A	Resources/ckeditor/_source/skins/kama/panel.css
A	Resources/ckeditor/_source/skins/kama/presets.css
A	Resources/ckeditor/_source/skins/kama/reset.css
A	Resources/ckeditor/_source/skins/kama/richcombo.css
A	Resources/ckeditor/_source/skins/kama/skin.js
A	Resources/ckeditor/_source/skins/kama/templates.css
A	Resources/ckeditor/_source/skins/kama/toolbar.css
A	Resources/ckeditor/_source/skins/office2003/dialog.css
A	Resources/ckeditor/_source/skins/office2003/editor.css
A	Resources/ckeditor/_source/skins/office2003/elementspath.css
A	Resources/ckeditor/_source/skins/office2003/icons.css
A	Resources/ckeditor/_source/skins/office2003/icons.png
A	Resources/ckeditor/_source/skins/office2003/icons_rtl.png
A	Resources/ckeditor/_source/skins/office2003/images/dialog_sides.gif
A	Resources/ckeditor/_source/skins/office2003/images/dialog_sides.png
A	Resources/ckeditor/_source/skins/office2003/images/dialog_sides_rtl.png
A	Resources/ckeditor/_source/skins/office2003/images/mini.gif
A	Resources/ckeditor/_source/skins/office2003/images/noimage.png
A	Resources/ckeditor/_source/skins/office2003/images/sprites.png
A	Resources/ckeditor/_source/skins/office2003/images/sprites_ie6.png
A	Resources/ckeditor/_source/skins/office2003/mainui.css
A	Resources/ckeditor/_source/skins/office2003/panel.css
A	Resources/ckeditor/_source/skins/office2003/presets.css
A	Resources/ckeditor/_source/skins/office2003/reset.css
A	Resources/ckeditor/_source/skins/office2003/richcombo.css
A	Resources/ckeditor/_source/skins/office2003/skin.js
A	Resources/ckeditor/_source/skins/office2003/templates.css
A	Resources/ckeditor/_source/skins/office2003/toolbar.css
A	Resources/ckeditor/_source/skins/v2/dialog.css
A	Resources/ckeditor/_source/skins/v2/editor.css
A	Resources/ckeditor/_source/skins/v2/elementspath.css
A	Resources/ckeditor/_source/skins/v2/icons.css
A	Resources/ckeditor/_source/skins/v2/icons.png
A	Resources/ckeditor/_source/skins/v2/icons_rtl.png
A	Resources/ckeditor/_source/skins/v2/images/dialog_sides.gif
A	Resources/ckeditor/_source/skins/v2/images/dialog_sides.png
A	Resources/ckeditor/_source/skins/v2/images/dialog_sides_rtl.png
A	Resources/ckeditor/_source/skins/v2/images/mini.gif
A	Resources/ckeditor/_source/skins/v2/images/noimage.png
A	Resources/ckeditor/_source/skins/v2/images/sprites.png
A	Resources/ckeditor/_source/skins/v2/images/sprites_ie6.png
A	Resources/ckeditor/_source/skins/v2/images/toolbar_start.gif
A	Resources/ckeditor/_source/skins/v2/mainui.css
A	Resources/ckeditor/_source/skins/v2/menu.css
A	Resources/ckeditor/_source/skins/v2/panel.css
A	Resources/ckeditor/_source/skins/v2/presets.css
A	Resources/ckeditor/_source/skins/v2/reset.css
A	Resources/ckeditor/_source/skins/v2/richcombo.css
A	Resources/ckeditor/_source/skins/v2/skin.js
A	Resources/ckeditor/_source/skins/v2/templates.css
A	Resources/ckeditor/_source/skins/v2/toolbar.css
A	Resources/ckeditor/_source/themes/default/theme.js
A	Resources/ckeditor/adapters/jquery.js
A	Resources/ckeditor/admin_otherinfo.php
A	Resources/ckeditor/ckeditor.asp
A	Resources/ckeditor/ckeditor.js
A	Resources/ckeditor/ckeditor.pack
A	Resources/ckeditor/ckeditor.php
A	Resources/ckeditor/ckeditor_basic.js
A	Resources/ckeditor/ckeditor_basic_source.js
A	Resources/ckeditor/ckeditor_php4.php
A	Resources/ckeditor/ckeditor_php5.php
A	Resources/ckeditor/ckeditor_source.js
A	Resources/ckeditor/ckfinder_php_2.2.1.zip
A	Resources/ckeditor/config.js
A	Resources/ckeditor/contents.css
A	Resources/ckeditor/email_2012-04-18.csv
A	Resources/ckeditor/images/spacer.gif
A	Resources/ckeditor/kefu_2012-04-20.csv
A	Resources/ckeditor/lang/_languages.js
A	Resources/ckeditor/lang/_translationstatus.txt
A	Resources/ckeditor/lang/af.js
A	Resources/ckeditor/lang/ar.js
A	Resources/ckeditor/lang/bg.js
A	Resources/ckeditor/lang/bn.js
A	Resources/ckeditor/lang/bs.js
A	Resources/ckeditor/lang/ca.js
A	Resources/ckeditor/lang/cs.js
A	Resources/ckeditor/lang/cy.js
A	Resources/ckeditor/lang/da.js
A	Resources/ckeditor/lang/de.js
A	Resources/ckeditor/lang/el.js
A	Resources/ckeditor/lang/en-au.js
A	Resources/ckeditor/lang/en-ca.js
A	Resources/ckeditor/lang/en-gb.js
A	Resources/ckeditor/lang/en.js
A	Resources/ckeditor/lang/eo.js
A	Resources/ckeditor/lang/es.js
A	Resources/ckeditor/lang/et.js
A	Resources/ckeditor/lang/eu.js
A	Resources/ckeditor/lang/fa.js
A	Resources/ckeditor/lang/fi.js
A	Resources/ckeditor/lang/fo.js
A	Resources/ckeditor/lang/fr-ca.js
A	Resources/ckeditor/lang/fr.js
A	Resources/ckeditor/lang/gl.js
A	Resources/ckeditor/lang/gu.js
A	Resources/ckeditor/lang/he.js
A	Resources/ckeditor/lang/hi.js
A	Resources/ckeditor/lang/hu.js
A	Resources/ckeditor/lang/is.js
A	Resources/ckeditor/lang/it.js
A	Resources/ckeditor/lang/ja.js
A	Resources/ckeditor/lang/ka.js
A	Resources/ckeditor/lang/km.js
A	Resources/ckeditor/lang/ko.js
A	Resources/ckeditor/lang/lt.js
A	Resources/ckeditor/lang/lv.js
A	Resources/ckeditor/lang/mn.js
A	Resources/ckeditor/lang/ms.js
A	Resources/ckeditor/lang/nb.js
A	Resources/ckeditor/lang/nl.js
A	Resources/ckeditor/lang/no.js
A	Resources/ckeditor/lang/pl.js
A	Resources/ckeditor/lang/pt-br.js
A	Resources/ckeditor/lang/pt.js
A	Resources/ckeditor/lang/ro.js
A	Resources/ckeditor/lang/ru.js
A	Resources/ckeditor/lang/sk.js
A	Resources/ckeditor/lang/sl.js
A	Resources/ckeditor/lang/sr-latn.js
A	Resources/ckeditor/lang/sr.js
A	Resources/ckeditor/lang/sv.js
A	Resources/ckeditor/lang/th.js
A	Resources/ckeditor/lang/tr.js
A	Resources/ckeditor/lang/uk.js
A	Resources/ckeditor/lang/vi.js
A	Resources/ckeditor/lang/zh-cn.js
A	Resources/ckeditor/lang/zh.js
A	Resources/ckeditor/member_2012-04-20.csv
A	Resources/ckeditor/plugins/a11yhelp/dialogs/a11yhelp.js
A	Resources/ckeditor/plugins/a11yhelp/lang/en.js
A	Resources/ckeditor/plugins/a11yhelp/lang/he.js
A	Resources/ckeditor/plugins/about/dialogs/about.js
A	Resources/ckeditor/plugins/about/dialogs/logo_ckeditor.png
A	Resources/ckeditor/plugins/adobeair/plugin.js
A	Resources/ckeditor/plugins/ajax/plugin.js
A	Resources/ckeditor/plugins/autogrow/plugin.js
A	Resources/ckeditor/plugins/bbcode/plugin.js
A	Resources/ckeditor/plugins/clipboard/dialogs/paste.js
A	Resources/ckeditor/plugins/colordialog/dialogs/colordialog.js
A	Resources/ckeditor/plugins/devtools/lang/en.js
A	Resources/ckeditor/plugins/devtools/plugin.js
A	Resources/ckeditor/plugins/dialog/dialogDefinition.js
A	Resources/ckeditor/plugins/div/dialogs/div.js
A	Resources/ckeditor/plugins/docprops/dialogs/docprops.js
A	Resources/ckeditor/plugins/docprops/plugin.js
A	Resources/ckeditor/plugins/find/dialogs/find.js
A	Resources/ckeditor/plugins/flash/dialogs/flash.js
A	Resources/ckeditor/plugins/flash/images/placeholder.png
A	Resources/ckeditor/plugins/forms/dialogs/button.js
A	Resources/ckeditor/plugins/forms/dialogs/checkbox.js
A	Resources/ckeditor/plugins/forms/dialogs/form.js
A	Resources/ckeditor/plugins/forms/dialogs/hiddenfield.js
A	Resources/ckeditor/plugins/forms/dialogs/radio.js
A	Resources/ckeditor/plugins/forms/dialogs/select.js
A	Resources/ckeditor/plugins/forms/dialogs/textarea.js
A	Resources/ckeditor/plugins/forms/dialogs/textfield.js
A	Resources/ckeditor/plugins/forms/images/hiddenfield.gif
A	Resources/ckeditor/plugins/iframe/dialogs/iframe.js
A	Resources/ckeditor/plugins/iframe/images/placeholder.png
A	Resources/ckeditor/plugins/iframedialog/plugin.js
A	Resources/ckeditor/plugins/image/dialogs/image.js
A	Resources/ckeditor/plugins/link/dialogs/anchor.js
A	Resources/ckeditor/plugins/link/dialogs/link.js
A	Resources/ckeditor/plugins/link/images/anchor.gif
A	Resources/ckeditor/plugins/liststyle/dialogs/liststyle.js
A	Resources/ckeditor/plugins/pagebreak/images/pagebreak.gif
A	Resources/ckeditor/plugins/pastefromword/filter/default.js
A	Resources/ckeditor/plugins/pastetext/dialogs/pastetext.js
A	Resources/ckeditor/plugins/placeholder/dialogs/placeholder.js
A	Resources/ckeditor/plugins/placeholder/lang/en.js
A	Resources/ckeditor/plugins/placeholder/lang/he.js
A	Resources/ckeditor/plugins/placeholder/placeholder.gif
A	Resources/ckeditor/plugins/scayt/dialogs/options.js
A	Resources/ckeditor/plugins/scayt/dialogs/toolbar.css
A	Resources/ckeditor/plugins/showblocks/images/block_address.png
A	Resources/ckeditor/plugins/showblocks/images/block_blockquote.png
A	Resources/ckeditor/plugins/showblocks/images/block_div.png
A	Resources/ckeditor/plugins/showblocks/images/block_h1.png
A	Resources/ckeditor/plugins/showblocks/images/block_h2.png
A	Resources/ckeditor/plugins/showblocks/images/block_h3.png
A	Resources/ckeditor/plugins/showblocks/images/block_h4.png
A	Resources/ckeditor/plugins/showblocks/images/block_h5.png
A	Resources/ckeditor/plugins/showblocks/images/block_h6.png
A	Resources/ckeditor/plugins/showblocks/images/block_p.png
A	Resources/ckeditor/plugins/showblocks/images/block_pre.png
A	Resources/ckeditor/plugins/smiley/dialogs/smiley.js
A	Resources/ckeditor/plugins/smiley/images/angel_smile.gif
A	Resources/ckeditor/plugins/smiley/images/angry_smile.gif
A	Resources/ckeditor/plugins/smiley/images/broken_heart.gif
A	Resources/ckeditor/plugins/smiley/images/confused_smile.gif
A	Resources/ckeditor/plugins/smiley/images/cry_smile.gif
A	Resources/ckeditor/plugins/smiley/images/devil_smile.gif
A	Resources/ckeditor/plugins/smiley/images/embaressed_smile.gif
A	Resources/ckeditor/plugins/smiley/images/envelope.gif
A	Resources/ckeditor/plugins/smiley/images/heart.gif
A	Resources/ckeditor/plugins/smiley/images/kiss.gif
A	Resources/ckeditor/plugins/smiley/images/lightbulb.gif
A	Resources/ckeditor/plugins/smiley/images/omg_smile.gif
A	Resources/ckeditor/plugins/smiley/images/regular_smile.gif
A	Resources/ckeditor/plugins/smiley/images/sad_smile.gif
A	Resources/ckeditor/plugins/smiley/images/shades_smile.gif
A	Resources/ckeditor/plugins/smiley/images/teeth_smile.gif
A	Resources/ckeditor/plugins/smiley/images/thumbs_down.gif
A	Resources/ckeditor/plugins/smiley/images/thumbs_up.gif
A	Resources/ckeditor/plugins/smiley/images/tounge_smile.gif
A	Resources/ckeditor/plugins/smiley/images/whatchutalkingabout_smile.gif
A	Resources/ckeditor/plugins/smiley/images/wink_smile.gif
A	Resources/ckeditor/plugins/specialchar/dialogs/specialchar.js
A	Resources/ckeditor/plugins/specialchar/lang/en.js
A	Resources/ckeditor/plugins/styles/styles/default.js
A	Resources/ckeditor/plugins/stylesheetparser/plugin.js
A	Resources/ckeditor/plugins/table/dialogs/table.js
A	Resources/ckeditor/plugins/tableresize/plugin.js
A	Resources/ckeditor/plugins/tabletools/dialogs/tableCell.js
A	Resources/ckeditor/plugins/templates/dialogs/templates.js
A	Resources/ckeditor/plugins/templates/templates/default.js
A	Resources/ckeditor/plugins/templates/templates/images/template1.gif
A	Resources/ckeditor/plugins/templates/templates/images/template2.gif
A	Resources/ckeditor/plugins/templates/templates/images/template3.gif
A	Resources/ckeditor/plugins/uicolor/dialogs/uicolor.js
A	Resources/ckeditor/plugins/uicolor/lang/en.js
A	Resources/ckeditor/plugins/uicolor/lang/he.js
A	Resources/ckeditor/plugins/uicolor/plugin.js
A	Resources/ckeditor/plugins/uicolor/uicolor.gif
A	Resources/ckeditor/plugins/uicolor/yui/assets/hue_bg.png
A	Resources/ckeditor/plugins/uicolor/yui/assets/hue_thumb.png
A	Resources/ckeditor/plugins/uicolor/yui/assets/picker_mask.png
A	Resources/ckeditor/plugins/uicolor/yui/assets/picker_thumb.png
A	Resources/ckeditor/plugins/uicolor/yui/assets/yui.css
A	Resources/ckeditor/plugins/uicolor/yui/yui.js
A	Resources/ckeditor/plugins/wsc/dialogs/ciframe.html
A	Resources/ckeditor/plugins/wsc/dialogs/tmpFrameset.html
A	Resources/ckeditor/plugins/wsc/dialogs/wsc.js
A	Resources/ckeditor/plugins/xml/plugin.js
A	Resources/ckeditor/skins/kama/dialog.css
A	Resources/ckeditor/skins/kama/editor.css
A	Resources/ckeditor/skins/kama/icons.png
A	Resources/ckeditor/skins/kama/icons_rtl.png
A	Resources/ckeditor/skins/kama/images/dialog_sides.gif
A	Resources/ckeditor/skins/kama/images/dialog_sides.png
A	Resources/ckeditor/skins/kama/images/dialog_sides_rtl.png
A	Resources/ckeditor/skins/kama/images/mini.gif
A	Resources/ckeditor/skins/kama/images/noimage.png
A	Resources/ckeditor/skins/kama/images/sprites.png
A	Resources/ckeditor/skins/kama/images/sprites_ie6.png
A	Resources/ckeditor/skins/kama/images/toolbar_start.gif
A	Resources/ckeditor/skins/kama/skin.js
A	Resources/ckeditor/skins/kama/templates.css
A	Resources/ckeditor/skins/office2003/dialog.css
A	Resources/ckeditor/skins/office2003/editor.css
A	Resources/ckeditor/skins/office2003/icons.png
A	Resources/ckeditor/skins/office2003/icons_rtl.png
A	Resources/ckeditor/skins/office2003/images/dialog_sides.gif
A	Resources/ckeditor/skins/office2003/images/dialog_sides.png
A	Resources/ckeditor/skins/office2003/images/dialog_sides_rtl.png
A	Resources/ckeditor/skins/office2003/images/mini.gif
A	Resources/ckeditor/skins/office2003/images/noimage.png
A	Resources/ckeditor/skins/office2003/images/sprites.png
A	Resources/ckeditor/skins/office2003/images/sprites_ie6.png
A	Resources/ckeditor/skins/office2003/skin.js
A	Resources/ckeditor/skins/office2003/templates.css
A	Resources/ckeditor/skins/v2/dialog.css
A	Resources/ckeditor/skins/v2/editor.css
A	Resources/ckeditor/skins/v2/icons.png
A	Resources/ckeditor/skins/v2/icons_rtl.png
A	Resources/ckeditor/skins/v2/images/dialog_sides.gif
A	Resources/ckeditor/skins/v2/images/dialog_sides.png
A	Resources/ckeditor/skins/v2/images/dialog_sides_rtl.png
A	Resources/ckeditor/skins/v2/images/mini.gif
A	Resources/ckeditor/skins/v2/images/noimage.png
A	Resources/ckeditor/skins/v2/images/sprites.png
A	Resources/ckeditor/skins/v2/images/sprites_ie6.png
A	Resources/ckeditor/skins/v2/images/toolbar_start.gif
A	Resources/ckeditor/skins/v2/skin.js
A	Resources/ckeditor/skins/v2/templates.css
A	Resources/ckeditor/themes/default/theme.js
A	Resources/ckfinder/_samples/ckeditor.html
A	Resources/ckfinder/_samples/fckeditor.html
A	Resources/ckfinder/_samples/index.html
A	Resources/ckfinder/_samples/php/ckeditor.php
A	Resources/ckfinder/_samples/php/fckeditor.php
A	Resources/ckfinder/_samples/php/popup.php
A	Resources/ckfinder/_samples/php/popups.php
A	Resources/ckfinder/_samples/php/standalone.php
A	Resources/ckfinder/_samples/popup.html
A	Resources/ckfinder/_samples/popups.html
A	Resources/ckfinder/_samples/public_api.html
A	Resources/ckfinder/_samples/sample.css
A	Resources/ckfinder/_samples/standalone.html
A	Resources/ckfinder/_samples/standalone_v1.html
A	Resources/ckfinder/changelog.txt
A	Resources/ckfinder/ckfinder.html
A	Resources/ckfinder/ckfinder.js
A	Resources/ckfinder/ckfinder.php
A	Resources/ckfinder/ckfinder_v1.js
A	Resources/ckfinder/config.js
A	Resources/ckfinder/config.php
A	Resources/ckfinder/core/ckfinder_php4.php
A	Resources/ckfinder/core/ckfinder_php5.php
A	Resources/ckfinder/core/connector/php/connector.php
A	Resources/ckfinder/core/connector/php/constants.php
A	Resources/ckfinder/core/connector/php/lang/bg.php
A	Resources/ckfinder/core/connector/php/lang/cs.php
A	Resources/ckfinder/core/connector/php/lang/da.php
A	Resources/ckfinder/core/connector/php/lang/de.php
A	Resources/ckfinder/core/connector/php/lang/el.php
A	Resources/ckfinder/core/connector/php/lang/en.php
A	Resources/ckfinder/core/connector/php/lang/eo.php
A	Resources/ckfinder/core/connector/php/lang/es-mx.php
A	Resources/ckfinder/core/connector/php/lang/es.php
A	Resources/ckfinder/core/connector/php/lang/et.php
A	Resources/ckfinder/core/connector/php/lang/fa.php
A	Resources/ckfinder/core/connector/php/lang/fi.php
A	Resources/ckfinder/core/connector/php/lang/fr.php
A	Resources/ckfinder/core/connector/php/lang/gu.php
A	Resources/ckfinder/core/connector/php/lang/he.php
A	Resources/ckfinder/core/connector/php/lang/hi.php
A	Resources/ckfinder/core/connector/php/lang/hr.php
A	Resources/ckfinder/core/connector/php/lang/hu.php
A	Resources/ckfinder/core/connector/php/lang/it.php
A	Resources/ckfinder/core/connector/php/lang/ja.php
A	Resources/ckfinder/core/connector/php/lang/lt.php
A	Resources/ckfinder/core/connector/php/lang/lv.php
A	Resources/ckfinder/core/connector/php/lang/nb.php
A	Resources/ckfinder/core/connector/php/lang/nl.php
A	Resources/ckfinder/core/connector/php/lang/nn.php
A	Resources/ckfinder/core/connector/php/lang/no.php
A	Resources/ckfinder/core/connector/php/lang/pl.php
A	Resources/ckfinder/core/connector/php/lang/pt-br.php
A	Resources/ckfinder/core/connector/php/lang/ro.php
A	Resources/ckfinder/core/connector/php/lang/ru.php
A	Resources/ckfinder/core/connector/php/lang/sk.php
A	Resources/ckfinder/core/connector/php/lang/sl.php
A	Resources/ckfinder/core/connector/php/lang/sv.php
A	Resources/ckfinder/core/connector/php/lang/tr.php
A	Resources/ckfinder/core/connector/php/lang/vi.php
A	Resources/ckfinder/core/connector/php/lang/zh-cn.php
A	Resources/ckfinder/core/connector/php/lang/zh-tw.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/CommandHandlerBase.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/CopyFiles.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/CreateFolder.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/DeleteFile.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/DeleteFolder.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/DownloadFile.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/FileUpload.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/GetFiles.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/GetFolders.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/Init.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/LoadCookies.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/MoveFiles.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/QuickUpload.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/RenameFile.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/RenameFolder.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/Thumbnail.php
A	Resources/ckfinder/core/connector/php/php4/CommandHandler/XmlCommandHandlerBase.php
A	Resources/ckfinder/core/connector/php/php4/Core/AccessControlConfig.php
A	Resources/ckfinder/core/connector/php/php4/Core/Config.php
A	Resources/ckfinder/core/connector/php/php4/Core/Connector.php
A	Resources/ckfinder/core/connector/php/php4/Core/Factory.php
A	Resources/ckfinder/core/connector/php/php4/Core/FolderHandler.php
A	Resources/ckfinder/core/connector/php/php4/Core/Hooks.php
A	Resources/ckfinder/core/connector/php/php4/Core/Registry.php
A	Resources/ckfinder/core/connector/php/php4/Core/ResourceTypeConfig.php
A	Resources/ckfinder/core/connector/php/php4/Core/ThumbnailsConfig.php
A	Resources/ckfinder/core/connector/php/php4/Core/Xml.php
A	Resources/ckfinder/core/connector/php/php4/ErrorHandler/Base.php
A	Resources/ckfinder/core/connector/php/php4/ErrorHandler/FileUpload.php
A	Resources/ckfinder/core/connector/php/php4/ErrorHandler/Http.php
A	Resources/ckfinder/core/connector/php/php4/ErrorHandler/QuickUpload.php
A	Resources/ckfinder/core/connector/php/php4/Utils/FileSystem.php
A	Resources/ckfinder/core/connector/php/php4/Utils/Misc.php
A	Resources/ckfinder/core/connector/php/php4/Utils/Security.php
A	Resources/ckfinder/core/connector/php/php4/Utils/XmlNode.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/CommandHandlerBase.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/CopyFiles.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/CreateFolder.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/DeleteFile.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/DeleteFolder.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/DownloadFile.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/FileUpload.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/GetFiles.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/GetFolders.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/Init.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/LoadCookies.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/MoveFiles.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/QuickUpload.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/RenameFile.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/RenameFolder.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/Thumbnail.php
A	Resources/ckfinder/core/connector/php/php5/CommandHandler/XmlCommandHandlerBase.php
A	Resources/ckfinder/core/connector/php/php5/Core/AccessControlConfig.php
A	Resources/ckfinder/core/connector/php/php5/Core/Config.php
A	Resources/ckfinder/core/connector/php/php5/Core/Connector.php
A	Resources/ckfinder/core/connector/php/php5/Core/Factory.php
A	Resources/ckfinder/core/connector/php/php5/Core/FolderHandler.php
A	Resources/ckfinder/core/connector/php/php5/Core/Hooks.php
A	Resources/ckfinder/core/connector/php/php5/Core/ImagesConfig.php
A	Resources/ckfinder/core/connector/php/php5/Core/Registry.php
A	Resources/ckfinder/core/connector/php/php5/Core/ResourceTypeConfig.php
A	Resources/ckfinder/core/connector/php/php5/Core/ThumbnailsConfig.php
A	Resources/ckfinder/core/connector/php/php5/Core/Xml.php
A	Resources/ckfinder/core/connector/php/php5/ErrorHandler/Base.php
A	Resources/ckfinder/core/connector/php/php5/ErrorHandler/FileUpload.php
A	Resources/ckfinder/core/connector/php/php5/ErrorHandler/Http.php
A	Resources/ckfinder/core/connector/php/php5/ErrorHandler/QuickUpload.php
A	Resources/ckfinder/core/connector/php/php5/Utils/FileSystem.php
A	Resources/ckfinder/core/connector/php/php5/Utils/Misc.php
A	Resources/ckfinder/core/connector/php/php5/Utils/Security.php
A	Resources/ckfinder/core/connector/php/php5/Utils/XmlNode.php
A	Resources/ckfinder/help/cs/files/001.html
A	Resources/ckfinder/help/cs/files/002.html
A	Resources/ckfinder/help/cs/files/003.html
A	Resources/ckfinder/help/cs/files/004.html
A	Resources/ckfinder/help/cs/files/005.html
A	Resources/ckfinder/help/cs/files/007.html
A	Resources/ckfinder/help/cs/files/008.html
A	Resources/ckfinder/help/cs/files/009.html
A	Resources/ckfinder/help/cs/files/010.html
A	Resources/ckfinder/help/cs/files/011.html
A	Resources/ckfinder/help/cs/files/012.html
A	Resources/ckfinder/help/cs/files/013.html
A	Resources/ckfinder/help/cs/files/014.html
A	Resources/ckfinder/help/cs/files/015.html
A	Resources/ckfinder/help/cs/files/header.html
A	Resources/ckfinder/help/cs/files/license.html
A	Resources/ckfinder/help/cs/files/suggestions.html
A	Resources/ckfinder/help/cs/files/toc.html
A	Resources/ckfinder/help/cs/index.html
A	Resources/ckfinder/help/en/files/001.html
A	Resources/ckfinder/help/en/files/002.html
A	Resources/ckfinder/help/en/files/003.html
A	Resources/ckfinder/help/en/files/004.html
A	Resources/ckfinder/help/en/files/005.html
A	Resources/ckfinder/help/en/files/006.html
A	Resources/ckfinder/help/en/files/007.html
A	Resources/ckfinder/help/en/files/008.html
A	Resources/ckfinder/help/en/files/009.html
A	Resources/ckfinder/help/en/files/010.html
A	Resources/ckfinder/help/en/files/011.html
A	Resources/ckfinder/help/en/files/012.html
A	Resources/ckfinder/help/en/files/013.html
A	Resources/ckfinder/help/en/files/014.html
A	Resources/ckfinder/help/en/files/015.html
A	Resources/ckfinder/help/en/files/header.html
A	Resources/ckfinder/help/en/files/license.html
A	Resources/ckfinder/help/en/files/suggestions.html
A	Resources/ckfinder/help/en/files/toc.html
A	Resources/ckfinder/help/en/index.html
A	Resources/ckfinder/help/es-mx/files/001.html
A	Resources/ckfinder/help/es-mx/files/002.html
A	Resources/ckfinder/help/es-mx/files/003.html
A	Resources/ckfinder/help/es-mx/files/004.html
A	Resources/ckfinder/help/es-mx/files/005.html
A	Resources/ckfinder/help/es-mx/files/006.html
A	Resources/ckfinder/help/es-mx/files/007.html
A	Resources/ckfinder/help/es-mx/files/008.html
A	Resources/ckfinder/help/es-mx/files/009.html
A	Resources/ckfinder/help/es-mx/files/010.html
A	Resources/ckfinder/help/es-mx/files/011.html
A	Resources/ckfinder/help/es-mx/files/012.html
A	Resources/ckfinder/help/es-mx/files/013.html
A	Resources/ckfinder/help/es-mx/files/header.html
A	Resources/ckfinder/help/es-mx/files/images/001.png
A	Resources/ckfinder/help/es-mx/files/images/002.gif
A	Resources/ckfinder/help/es-mx/files/images/003.gif
A	Resources/ckfinder/help/es-mx/files/images/004.png
A	Resources/ckfinder/help/es-mx/files/images/005.png
A	Resources/ckfinder/help/es-mx/files/images/006.png
A	Resources/ckfinder/help/es-mx/files/images/007.png
A	Resources/ckfinder/help/es-mx/files/images/008.png
A	Resources/ckfinder/help/es-mx/files/images/009.png
A	Resources/ckfinder/help/es-mx/files/images/010.gif
A	Resources/ckfinder/help/es-mx/files/images/011.png
A	Resources/ckfinder/help/es-mx/files/images/012.png
A	Resources/ckfinder/help/es-mx/files/images/013.png
A	Resources/ckfinder/help/es-mx/files/images/014.gif
A	Resources/ckfinder/help/es-mx/files/images/015.gif
A	Resources/ckfinder/help/es-mx/files/images/016.gif
A	Resources/ckfinder/help/es-mx/files/images/017.gif
A	Resources/ckfinder/help/es-mx/files/images/018.png
A	Resources/ckfinder/help/es-mx/files/images/019.png
A	Resources/ckfinder/help/es-mx/files/images/020.png
A	Resources/ckfinder/help/es-mx/files/license.html
A	Resources/ckfinder/help/es-mx/files/suggestions.html
A	Resources/ckfinder/help/es-mx/files/toc.html
A	Resources/ckfinder/help/es/files/001.html
A	Resources/ckfinder/help/es/files/002.html
A	Resources/ckfinder/help/es/files/003.html
A	Resources/ckfinder/help/es/files/004.html
A	Resources/ckfinder/help/es/files/005.html
A	Resources/ckfinder/help/es/files/006.html
A	Resources/ckfinder/help/es/files/007.html
A	Resources/ckfinder/help/es/files/008.html
A	Resources/ckfinder/help/es/files/009.html
A	Resources/ckfinder/help/es/files/010.html
A	Resources/ckfinder/help/es/files/011.html
A	Resources/ckfinder/help/es/files/012.html
A	Resources/ckfinder/help/es/files/013.html
A	Resources/ckfinder/help/es/files/header.html
A	Resources/ckfinder/help/es/files/images/001.png
A	Resources/ckfinder/help/es/files/images/002.gif
A	Resources/ckfinder/help/es/files/images/003.gif
A	Resources/ckfinder/help/es/files/images/004.png
A	Resources/ckfinder/help/es/files/images/005.png
A	Resources/ckfinder/help/es/files/images/006.png
A	Resources/ckfinder/help/es/files/images/007.png
A	Resources/ckfinder/help/es/files/images/008.png
A	Resources/ckfinder/help/es/files/images/009.png
A	Resources/ckfinder/help/es/files/images/010.gif
A	Resources/ckfinder/help/es/files/images/011.png
A	Resources/ckfinder/help/es/files/images/012.png
A	Resources/ckfinder/help/es/files/images/013.png
A	Resources/ckfinder/help/es/files/images/014.gif
A	Resources/ckfinder/help/es/files/images/015.gif
A	Resources/ckfinder/help/es/files/images/016.gif
A	Resources/ckfinder/help/es/files/images/017.gif
A	Resources/ckfinder/help/es/files/images/018.png
A	Resources/ckfinder/help/es/files/images/019.png
A	Resources/ckfinder/help/es/files/images/020.png
A	Resources/ckfinder/help/es/files/license.html
A	Resources/ckfinder/help/es/files/suggestions.html
A	Resources/ckfinder/help/es/files/toc.html
A	Resources/ckfinder/help/es/index.html
A	Resources/ckfinder/help/fi/files/001.html
A	Resources/ckfinder/help/fi/files/002.html
A	Resources/ckfinder/help/fi/files/003.html
A	Resources/ckfinder/help/fi/files/004.html
A	Resources/ckfinder/help/fi/files/005.html
A	Resources/ckfinder/help/fi/files/006.html
A	Resources/ckfinder/help/fi/files/007.html
A	Resources/ckfinder/help/fi/files/008.html
A	Resources/ckfinder/help/fi/files/009.html
A	Resources/ckfinder/help/fi/files/010.html
A	Resources/ckfinder/help/fi/files/011.html
A	Resources/ckfinder/help/fi/files/012.html
A	Resources/ckfinder/help/fi/files/013.html
A	Resources/ckfinder/help/fi/files/header.html
A	Resources/ckfinder/help/fi/files/images/001.gif
A	Resources/ckfinder/help/fi/files/images/002.gif
A	Resources/ckfinder/help/fi/files/images/003.gif
A	Resources/ckfinder/help/fi/files/images/004.gif
A	Resources/ckfinder/help/fi/files/images/005.gif
A	Resources/ckfinder/help/fi/files/images/006.gif
A	Resources/ckfinder/help/fi/files/images/007.gif
A	Resources/ckfinder/help/fi/files/images/008.gif
A	Resources/ckfinder/help/fi/files/images/009.gif
A	Resources/ckfinder/help/fi/files/images/010.gif
A	Resources/ckfinder/help/fi/files/images/011.gif
A	Resources/ckfinder/help/fi/files/images/012.gif
A	Resources/ckfinder/help/fi/files/images/013.gif
A	Resources/ckfinder/help/fi/files/images/014.gif
A	Resources/ckfinder/help/fi/files/images/015.gif
A	Resources/ckfinder/help/fi/files/images/016.gif
A	Resources/ckfinder/help/fi/files/images/017.gif
A	Resources/ckfinder/help/fi/files/images/018.gif
A	Resources/ckfinder/help/fi/files/images/019.gif
A	Resources/ckfinder/help/fi/files/license.html
A	Resources/ckfinder/help/fi/files/suggestions.html
A	Resources/ckfinder/help/fi/files/toc.html
A	Resources/ckfinder/help/fi/index.html
A	Resources/ckfinder/help/files/images/002.gif
A	Resources/ckfinder/help/files/images/003.gif
A	Resources/ckfinder/help/files/images/CKFinder_basket_clear.png
A	Resources/ckfinder/help/files/images/CKFinder_basket_drag.png
A	Resources/ckfinder/help/files/images/CKFinder_basket_empty.png
A	Resources/ckfinder/help/files/images/CKFinder_basket_file_menu.png
A	Resources/ckfinder/help/files/images/CKFinder_basket_remove.png
A	Resources/ckfinder/help/files/images/CKFinder_file_already_exists.png
A	Resources/ckfinder/help/files/images/CKFinder_file_copied.png
A	Resources/ckfinder/help/files/images/CKFinder_file_delete.png
A	Resources/ckfinder/help/files/images/CKFinder_file_display_01.png
A	Resources/ckfinder/help/files/images/CKFinder_file_display_02.png
A	Resources/ckfinder/help/files/images/CKFinder_file_display_03.png
A	Resources/ckfinder/help/files/images/CKFinder_file_display_04.png
A	Resources/ckfinder/help/files/images/CKFinder_file_drag_copy.png
A	Resources/ckfinder/help/files/images/CKFinder_file_drag_move.png
A	Resources/ckfinder/help/files/images/CKFinder_file_menu.png
A	Resources/ckfinder/help/files/images/CKFinder_file_moved.png
A	Resources/ckfinder/help/files/images/CKFinder_file_pane.png
A	Resources/ckfinder/help/files/images/CKFinder_file_rename.png
A	Resources/ckfinder/help/files/images/CKFinder_file_resize.png
A	Resources/ckfinder/help/files/images/CKFinder_file_resize_both.png
A	Resources/ckfinder/help/files/images/CKFinder_file_resize_new.png
A	Resources/ckfinder/help/files/images/CKFinder_file_resize_overwrite.png
A	Resources/ckfinder/help/files/images/CKFinder_file_resize_resized.png
A	Resources/ckfinder/help/files/images/CKFinder_file_resize_thumbnails.png
A	Resources/ckfinder/help/files/images/CKFinder_file_select_hovered.png
A	Resources/ckfinder/help/files/images/CKFinder_file_select_selected.png
A	Resources/ckfinder/help/files/images/CKFinder_file_select_unselected.png
A	Resources/ckfinder/help/files/images/CKFinder_file_view_list.png
A	Resources/ckfinder/help/files/images/CKFinder_file_view_thumbnails.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_collapse.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_copied_from_basket.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_delete.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_expand.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_loading.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_menu.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_moved_from_basket.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_new.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_pane.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_rename.png
A	Resources/ckfinder/help/files/images/CKFinder_folder_select.png
A	Resources/ckfinder/help/files/images/CKFinder_interface.png
A	Resources/ckfinder/help/files/images/CKFinder_menu_arrow.png
A	Resources/ckfinder/help/files/images/CKFinder_menu_arrows.png
A	Resources/ckfinder/help/files/images/CKFinder_resize_lock.png
A	Resources/ckfinder/help/files/images/CKFinder_resize_reset.png
A	Resources/ckfinder/help/files/images/CKFinder_resize_unlock.png
A	Resources/ckfinder/help/files/images/CKFinder_settings.png
A	Resources/ckfinder/help/files/images/CKFinder_status_empty.png
A	Resources/ckfinder/help/files/images/CKFinder_status_file.png
A	Resources/ckfinder/help/files/images/CKFinder_toolbar.png
A	Resources/ckfinder/help/files/images/CKFinder_toolbar_help.png
A	Resources/ckfinder/help/files/images/CKFinder_toolbar_refresh.png
A	Resources/ckfinder/help/files/images/CKFinder_upload_01.png
A	Resources/ckfinder/help/files/images/CKFinder_upload_03.png
A	Resources/ckfinder/help/files/images/CKFinder_upload_04.png
A	Resources/ckfinder/help/files/images/CKFinder_upload_09.png
A	Resources/ckfinder/help/files/images/CKFinder_upload_10.png
A	Resources/ckfinder/help/files/other/help.css
A	Resources/ckfinder/help/files/other/help.js
A	Resources/ckfinder/help/lt/files/001.html
A	Resources/ckfinder/help/lt/files/002.html
A	Resources/ckfinder/help/lt/files/003.html
A	Resources/ckfinder/help/lt/files/004.html
A	Resources/ckfinder/help/lt/files/005.html
A	Resources/ckfinder/help/lt/files/006.html
A	Resources/ckfinder/help/lt/files/007.html
A	Resources/ckfinder/help/lt/files/008.html
A	Resources/ckfinder/help/lt/files/009.html
A	Resources/ckfinder/help/lt/files/010.html
A	Resources/ckfinder/help/lt/files/011.html
A	Resources/ckfinder/help/lt/files/012.html
A	Resources/ckfinder/help/lt/files/013.html
A	Resources/ckfinder/help/lt/files/header.html
A	Resources/ckfinder/help/lt/files/images/001.gif
A	Resources/ckfinder/help/lt/files/images/002.gif
A	Resources/ckfinder/help/lt/files/images/003.gif
A	Resources/ckfinder/help/lt/files/images/004.gif
A	Resources/ckfinder/help/lt/files/images/005.gif
A	Resources/ckfinder/help/lt/files/images/006.gif
A	Resources/ckfinder/help/lt/files/images/007.gif
A	Resources/ckfinder/help/lt/files/images/008.gif
A	Resources/ckfinder/help/lt/files/images/009.gif
A	Resources/ckfinder/help/lt/files/images/010.gif
A	Resources/ckfinder/help/lt/files/images/011.gif
A	Resources/ckfinder/help/lt/files/images/012.gif
A	Resources/ckfinder/help/lt/files/images/013.gif
A	Resources/ckfinder/help/lt/files/images/014.gif
A	Resources/ckfinder/help/lt/files/images/015.gif
A	Resources/ckfinder/help/lt/files/images/016.gif
A	Resources/ckfinder/help/lt/files/images/017.gif
A	Resources/ckfinder/help/lt/files/images/018.gif
A	Resources/ckfinder/help/lt/files/images/019.gif
A	Resources/ckfinder/help/lt/files/images/020.gif
A	Resources/ckfinder/help/lt/files/license.html
A	Resources/ckfinder/help/lt/files/suggestions.html
A	Resources/ckfinder/help/lt/files/toc.html
A	Resources/ckfinder/help/lt/index.html
A	Resources/ckfinder/help/pl/files/001.html
A	Resources/ckfinder/help/pl/files/002.html
A	Resources/ckfinder/help/pl/files/003.html
A	Resources/ckfinder/help/pl/files/004.html
A	Resources/ckfinder/help/pl/files/005.html
A	Resources/ckfinder/help/pl/files/006.html
A	Resources/ckfinder/help/pl/files/007.html
A	Resources/ckfinder/help/pl/files/008.html
A	Resources/ckfinder/help/pl/files/009.html
A	Resources/ckfinder/help/pl/files/010.html
A	Resources/ckfinder/help/pl/files/011.html
A	Resources/ckfinder/help/pl/files/012.html
A	Resources/ckfinder/help/pl/files/013.html
A	Resources/ckfinder/help/pl/files/014.html
A	Resources/ckfinder/help/pl/files/015.html
A	Resources/ckfinder/help/pl/files/header.html
A	Resources/ckfinder/help/pl/files/license.html
A	Resources/ckfinder/help/pl/files/suggestions.html
A	Resources/ckfinder/help/pl/files/toc.html
A	Resources/ckfinder/help/pl/index.html
A	Resources/ckfinder/install.txt
A	Resources/ckfinder/lang/_translationstatus.txt
A	Resources/ckfinder/lang/bg.js
A	Resources/ckfinder/lang/cy.js
A	Resources/ckfinder/lang/da.js
A	Resources/ckfinder/lang/de.js
A	Resources/ckfinder/lang/el.js
A	Resources/ckfinder/lang/en.js
A	Resources/ckfinder/lang/eo.js
A	Resources/ckfinder/lang/es-mx.js
A	Resources/ckfinder/lang/es.js
A	Resources/ckfinder/lang/et.js
A	Resources/ckfinder/lang/fa.js
A	Resources/ckfinder/lang/fi.js
A	Resources/ckfinder/lang/fr.js
A	Resources/ckfinder/lang/gu.js
A	Resources/ckfinder/lang/he.js
A	Resources/ckfinder/lang/hi.js
A	Resources/ckfinder/lang/hr.js
A	Resources/ckfinder/lang/hu.js
A	Resources/ckfinder/lang/it.js
A	Resources/ckfinder/lang/ja.js
A	Resources/ckfinder/lang/lt.js
A	Resources/ckfinder/lang/lv.js
A	Resources/ckfinder/lang/nb.js
A	Resources/ckfinder/lang/nl.js
A	Resources/ckfinder/lang/nn.js
A	Resources/ckfinder/lang/no.js
A	Resources/ckfinder/lang/pl.js
A	Resources/ckfinder/lang/pt-br.js
A	Resources/ckfinder/lang/ro.js
A	Resources/ckfinder/lang/ru.js
A	Resources/ckfinder/lang/sk.js
A	Resources/ckfinder/lang/sl.js
A	Resources/ckfinder/lang/sv.js
A	Resources/ckfinder/lang/tr.js
A	Resources/ckfinder/lang/vi.js
A	Resources/ckfinder/lang/zh-cn.js
A	Resources/ckfinder/lang/zh-tw.js
A	Resources/ckfinder/license.txt
A	Resources/ckfinder/plugins/dummy/lang/en.js
A	Resources/ckfinder/plugins/dummy/lang/pl.js
A	Resources/ckfinder/plugins/dummy/plugin.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/LICENSE
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/csharp/css/csharpcolors.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/csharp/js/parsecsharp.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/csharp/js/tokenizecsharp.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/php/LICENSE
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/php/css/phpcolors.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/php/js/parsephp.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/php/js/parsephphtmlmixed.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/contrib/php/js/tokenizephp.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/css/csscolors.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/css/docs.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/css/font.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/css/jscolors.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/css/sparqlcolors.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/css/xmlcolors.css
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/codemirror.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/editor.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/highlight.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/mirrorframe.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/parsecss.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/parsedummy.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/parsehtmlmixed.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/parsejavascript.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/parsesparql.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/parsexml.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/select.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/stringstream.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/tokenize.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/tokenizejavascript.js
A	Resources/ckfinder/plugins/fileeditor/codemirror/js/util.js
A	Resources/ckfinder/plugins/fileeditor/plugin.js
A	Resources/ckfinder/plugins/fileeditor/plugin.php
A	Resources/ckfinder/plugins/flashupload/Uploader.html
A	Resources/ckfinder/plugins/flashupload/flash/Uploader.swf
A	Resources/ckfinder/plugins/gallery/colorbox/colorbox.css
A	Resources/ckfinder/plugins/gallery/colorbox/images/border.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/controls.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderBottomCenter.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderBottomLeft.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderBottomRight.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderMiddleLeft.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderMiddleRight.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderTopCenter.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderTopLeft.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/ie6/borderTopRight.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/loading.gif
A	Resources/ckfinder/plugins/gallery/colorbox/images/loading_background.png
A	Resources/ckfinder/plugins/gallery/colorbox/images/overlay.png
A	Resources/ckfinder/plugins/gallery/colorbox/jquery.colorbox-min.js
A	Resources/ckfinder/plugins/gallery/colorbox/jquery.min.js
A	Resources/ckfinder/plugins/gallery/colorbox/license.txt
A	Resources/ckfinder/plugins/imageresize/images/mini.gif
A	Resources/ckfinder/plugins/imageresize/plugin.js
A	Resources/ckfinder/plugins/imageresize/plugin.php
A	Resources/ckfinder/plugins/watermark/logo.gif
A	Resources/ckfinder/plugins/watermark/plugin.php
A	Resources/ckfinder/skins/kama/app.css
A	Resources/ckfinder/skins/kama/host.css
A	Resources/ckfinder/skins/kama/images/ckffolder.gif
A	Resources/ckfinder/skins/kama/images/ckffolderopened.gif
A	Resources/ckfinder/skins/kama/images/ckfminus.gif
A	Resources/ckfinder/skins/kama/images/ckfnothumb.gif
A	Resources/ckfinder/skins/kama/images/ckfplus.gif
A	Resources/ckfinder/skins/kama/images/icons.png
A	Resources/ckfinder/skins/kama/images/icons/16/ai.gif
A	Resources/ckfinder/skins/kama/images/icons/16/avi.gif
A	Resources/ckfinder/skins/kama/images/icons/16/bmp.gif
A	Resources/ckfinder/skins/kama/images/icons/16/cs.gif
A	Resources/ckfinder/skins/kama/images/icons/16/default.icon.gif
A	Resources/ckfinder/skins/kama/images/icons/16/dll.gif
A	Resources/ckfinder/skins/kama/images/icons/16/doc.gif
A	Resources/ckfinder/skins/kama/images/icons/16/docx.gif
A	Resources/ckfinder/skins/kama/images/icons/16/exe.gif
A	Resources/ckfinder/skins/kama/images/icons/16/fla.gif
A	Resources/ckfinder/skins/kama/images/icons/16/gif.gif
A	Resources/ckfinder/skins/kama/images/icons/16/jpg.gif
A	Resources/ckfinder/skins/kama/images/icons/16/js.gif
A	Resources/ckfinder/skins/kama/images/icons/16/mdb.gif
A	Resources/ckfinder/skins/kama/images/icons/16/mp3.gif
A	Resources/ckfinder/skins/kama/images/icons/16/ogg.gif
A	Resources/ckfinder/skins/kama/images/icons/16/pdf.gif
A	Resources/ckfinder/skins/kama/images/icons/16/ppt.gif
A	Resources/ckfinder/skins/kama/images/icons/16/pptx.gif
A	Resources/ckfinder/skins/kama/images/icons/16/rdp.gif
A	Resources/ckfinder/skins/kama/images/icons/16/swf.gif
A	Resources/ckfinder/skins/kama/images/icons/16/swt.gif
A	Resources/ckfinder/skins/kama/images/icons/16/txt.gif
A	Resources/ckfinder/skins/kama/images/icons/16/vsd.gif
A	Resources/ckfinder/skins/kama/images/icons/16/xlsx.gif
A	Resources/ckfinder/skins/kama/images/icons/16/xml.gif
A	Resources/ckfinder/skins/kama/images/icons/16/zip.gif
A	Resources/ckfinder/skins/kama/images/icons/32/ai.gif
A	Resources/ckfinder/skins/kama/images/icons/32/avi.gif
A	Resources/ckfinder/skins/kama/images/icons/32/bmp.gif
A	Resources/ckfinder/skins/kama/images/icons/32/cs.gif
A	Resources/ckfinder/skins/kama/images/icons/32/default.icon.gif
A	Resources/ckfinder/skins/kama/images/icons/32/dll.gif
A	Resources/ckfinder/skins/kama/images/icons/32/doc.gif
A	Resources/ckfinder/skins/kama/images/icons/32/docx.gif
A	Resources/ckfinder/skins/kama/images/icons/32/exe.gif
A	Resources/ckfinder/skins/kama/images/icons/32/fla.gif
A	Resources/ckfinder/skins/kama/images/icons/32/gif.gif
A	Resources/ckfinder/skins/kama/images/icons/32/jpg.gif
A	Resources/ckfinder/skins/kama/images/icons/32/js.gif
A	Resources/ckfinder/skins/kama/images/icons/32/mdb.gif
A	Resources/ckfinder/skins/kama/images/icons/32/mp3.gif
A	Resources/ckfinder/skins/kama/images/icons/32/ogg.gif
A	Resources/ckfinder/skins/kama/images/icons/32/ogg.png
A	Resources/ckfinder/skins/kama/images/icons/32/pdf.gif
A	Resources/ckfinder/skins/kama/images/icons/32/ppt.gif
A	Resources/ckfinder/skins/kama/images/icons/32/pptx.gif
A	Resources/ckfinder/skins/kama/images/icons/32/rdp.gif
A	Resources/ckfinder/skins/kama/images/icons/32/swf.gif
A	Resources/ckfinder/skins/kama/images/icons/32/swt.gif
A	Resources/ckfinder/skins/kama/images/icons/32/txt.gif
A	Resources/ckfinder/skins/kama/images/icons/32/vsd.gif
A	Resources/ckfinder/skins/kama/images/icons/32/xls.gif
A	Resources/ckfinder/skins/kama/images/icons/32/xlsx.gif
A	Resources/ckfinder/skins/kama/images/icons/32/xml.gif
A	Resources/ckfinder/skins/kama/images/icons/32/zip.gif
A	Resources/ckfinder/skins/kama/images/loaders/16x16.gif
A	Resources/ckfinder/skins/kama/images/loaders/32x32.gif
A	Resources/ckfinder/skins/kama/images/spacer.gif
A	Resources/ckfinder/skins/kama/images/sprites.png
A	Resources/ckfinder/skins/kama/images/sprites_ie6.png
A	Resources/ckfinder/skins/kama/images/toolbar/add.gif
A	Resources/ckfinder/skins/kama/images/toolbar/clear_basket.gif
A	Resources/ckfinder/skins/kama/images/toolbar/delete.gif
A	Resources/ckfinder/skins/kama/images/toolbar/download.gif
A	Resources/ckfinder/skins/kama/images/toolbar/help.gif
A	Resources/ckfinder/skins/kama/images/toolbar/refresh.gif
A	Resources/ckfinder/skins/kama/images/toolbar/settings.gif
A	Resources/ckfinder/skins/kama/images/toolbar/view.gif
A	Resources/ckfinder/skins/kama/richcombo.css
A	Resources/ckfinder/skins/kama/skin.js
A	Resources/ckfinder/skins/kama/uipanel.css
A	Resources/ckfinder/skins/v1/app.css
A	Resources/ckfinder/skins/v1/host.css
A	Resources/ckfinder/skins/v1/images/ckffolder.gif
A	Resources/ckfinder/skins/v1/images/ckffolderopened.gif
A	Resources/ckfinder/skins/v1/images/ckfminus.gif
A	Resources/ckfinder/skins/v1/images/ckfnothumb.gif
A	Resources/ckfinder/skins/v1/images/ckfplus.gif
A	Resources/ckfinder/skins/v1/images/dialog_sides.gif
A	Resources/ckfinder/skins/v1/images/dialog_sides.png
A	Resources/ckfinder/skins/v1/images/dialog_sides_rtl.png
A	Resources/ckfinder/skins/v1/images/icons.png
A	Resources/ckfinder/skins/v1/images/icons/16/ai.gif
A	Resources/ckfinder/skins/v1/images/icons/16/avi.gif
A	Resources/ckfinder/skins/v1/images/icons/16/bmp.gif
A	Resources/ckfinder/skins/v1/images/icons/16/cs.gif
A	Resources/ckfinder/skins/v1/images/icons/16/dll.gif
A	Resources/ckfinder/skins/v1/images/icons/16/doc.gif
A	Resources/ckfinder/skins/v1/images/icons/16/docx.gif
A	Resources/ckfinder/skins/v1/images/icons/16/exe.gif
A	Resources/ckfinder/skins/v1/images/icons/16/fla.gif
A	Resources/ckfinder/skins/v1/images/icons/16/gif.gif
A	Resources/ckfinder/skins/v1/images/icons/16/jpg.gif
A	Resources/ckfinder/skins/v1/images/icons/16/js.gif
A	Resources/ckfinder/skins/v1/images/icons/16/mdb.gif
A	Resources/ckfinder/skins/v1/images/icons/16/mp3.gif
A	Resources/ckfinder/skins/v1/images/icons/16/pdf.gif
A	Resources/ckfinder/skins/v1/images/icons/16/ppt.gif
A	Resources/ckfinder/skins/v1/images/icons/16/pptx.gif
A	Resources/ckfinder/skins/v1/images/icons/16/rdp.gif
A	Resources/ckfinder/skins/v1/images/icons/16/swf.gif
A	Resources/ckfinder/skins/v1/images/icons/16/swt.gif
A	Resources/ckfinder/skins/v1/images/icons/16/txt.gif
A	Resources/ckfinder/skins/v1/images/icons/16/vsd.gif
A	Resources/ckfinder/skins/v1/images/icons/16/xls.gif
A	Resources/ckfinder/skins/v1/images/icons/16/xlsx.gif
A	Resources/ckfinder/skins/v1/images/icons/16/xml.gif
A	Resources/ckfinder/skins/v1/images/icons/16/zip.gif
A	Resources/ckfinder/skins/v1/images/icons/32/ai.gif
A	Resources/ckfinder/skins/v1/images/icons/32/avi.gif
A	Resources/ckfinder/skins/v1/images/icons/32/bmp.gif
A	Resources/ckfinder/skins/v1/images/icons/32/cs.gif
A	Resources/ckfinder/skins/v1/images/icons/32/default.icon.gif
A	Resources/ckfinder/skins/v1/images/icons/32/dll.gif
A	Resources/ckfinder/skins/v1/images/icons/32/doc.gif
A	Resources/ckfinder/skins/v1/images/icons/32/docx.gif
A	Resources/ckfinder/skins/v1/images/icons/32/exe.gif
A	Resources/ckfinder/skins/v1/images/icons/32/fla.gif
A	Resources/ckfinder/skins/v1/images/icons/32/gif.gif
A	Resources/ckfinder/skins/v1/images/icons/32/jpg.gif
A	Resources/ckfinder/skins/v1/images/icons/32/js.gif
A	Resources/ckfinder/skins/v1/images/icons/32/mdb.gif
A	Resources/ckfinder/skins/v1/images/icons/32/mp3.gif
A	Resources/ckfinder/skins/v1/images/icons/32/pdf.gif
A	Resources/ckfinder/skins/v1/images/icons/32/ppt.gif
A	Resources/ckfinder/skins/v1/images/icons/32/pptx.gif
A	Resources/ckfinder/skins/v1/images/icons/32/rdp.gif
A	Resources/ckfinder/skins/v1/images/icons/32/swf.gif
A	Resources/ckfinder/skins/v1/images/icons/32/swt.gif
A	Resources/ckfinder/skins/v1/images/icons/32/txt.gif
A	Resources/ckfinder/skins/v1/images/icons/32/vsd.gif
A	Resources/ckfinder/skins/v1/images/icons/32/xls.gif
A	Resources/ckfinder/skins/v1/images/icons/32/xlsx.gif
A	Resources/ckfinder/skins/v1/images/icons/32/xml.gif
A	Resources/ckfinder/skins/v1/images/icons/32/zip.gif
A	Resources/ckfinder/skins/v1/images/loaders/16x16.gif
A	Resources/ckfinder/skins/v1/images/loaders/32x32.gif
A	Resources/ckfinder/skins/v1/images/spacer.gif
A	Resources/ckfinder/skins/v1/images/sprites.png
A	Resources/ckfinder/skins/v1/images/sprites_ie6.png
A	Resources/ckfinder/skins/v1/images/toolbar/add.gif
A	Resources/ckfinder/skins/v1/images/toolbar/clear_basket.gif
A	Resources/ckfinder/skins/v1/images/toolbar/delete.gif
A	Resources/ckfinder/skins/v1/images/toolbar/download.gif
A	Resources/ckfinder/skins/v1/images/toolbar/help.gif
A	Resources/ckfinder/skins/v1/images/toolbar/refresh.gif
A	Resources/ckfinder/skins/v1/images/toolbar/settings.gif
A	Resources/ckfinder/skins/v1/images/toolbar/view.gif
A	Resources/ckfinder/skins/v1/images/toolbar_start.gif
A	Resources/ckfinder/skins/v1/richcombo.css
A	Resources/ckfinder/skins/v1/uipanel.css
A	Resources/ckfinder/translations.txt
A	Resources/ckfinder/userfiles/.htaccess
M	advertising/horse.php
D	archive_out/wordpress.php
D	images/banner_about.jpg
M	include/include_juheshopproduct.php
M	include/include_juheshopproduct2.php
M	include/include_juheshopproduct_month.php
M	include/include_juheshopproduct_month1.php
M	include/include_recshop.php
M	include/include_saleshopproduct.php
A	js/jquery.min.js
M	language/big5/Desktop_Pack_Ex.php
M	language/big5_old/Visit_Pack.php
M	member/shop_goods_ajax_pic.php
M	member/shop_goods_ajax_saleoffe.php
M	member/shop_goods_ajax_saleoffe_save.php
M	member/shop_goods_ajax_saleoffeadd.php
M	member/shop_goods_list.php
M	member/shopcomment.php
M	member/shopcomment_save.php
M	modules/sync/ap_goods_sync.php
M	modules/sync/common.php
A	photo/monoslideshow.swf
A	photo/photo.php
A	photo/photoindex.php
A	poll/poll.php
A	poll/poll_action.php
A	print/article.php
A	print/article_c_list.php
A	print/article_class.php
A	print/article_class_print.php
A	print/article_service_class.php
A	print/article_tag.php
A	print/calendar.php
A	print/faq.php
A	print/index.php
A	print/join.php
A	print/mailtofriend.php
A	print/snatchesofnews_I.php
M	product/product_class_list.php
M	search/shop_search.php
M	shop/shop_comment.php
A	shop/shop_goods_ajax_pic.php
A	shop/shop_goods_ajax_pic_save.php
M	shop/shop_top.php
M	shop/shoplist.php
M	shopadmin/Check_Admin.php
M	shopadmin/admin_bonus_manager.php
M	shopadmin/admin_goods_ajax_detail.php
M	shopadmin/admin_goods_ajax_detail_save.php
M	shopadmin/admin_goods_ajax_saleoffe.php
M	shopadmin/admin_goods_ajax_saleoffe_save.php
M	shopadmin/admin_goods_ajax_saleoffeadd.php
M	shopadmin/admin_goods_excel.php
M	shopadmin/admin_linkgoods.php
M	shopadmin/admin_operater.php
M	shopadmin/admin_operater_list.php
M	shopadmin/admin_operater_save.php
M	shopadmin/admin_order_excel.php
M	shopadmin/admin_ptype.php
M	shopadmin/admin_shop.php
M	shopadmin/admin_shop_list.php
M	shopadmin/admin_shop_save.php
M	shopadmin/desktop.php
M	shopadmin/provider_memberprice_save.php
M	shopping/cart.class.php
M	shopping/shopping.php
A	store/article.php
A	store/article_c_list.php
A	store/article_class.php
A	store/article_class_print.php
A	store/article_service_class.php
A	store/article_tag.php
A	store/calendar.php
A	store/faq.php
A	store/index.php
A	store/join.php
A	store/mailtofriend.php
A	store/snatchesofnews_I.php
A	study/study.php
A	study/study_class.php
A	study/study_index.php
M	templates/freewant/bottom.html
A	templates/freewant/images/13663719561319.gif
M	templates/freewant/images/logo.jpg
M	templates/freewant/images2/shop-r005.gif
M	templates/freewant/index_groupon.html
M	templates/freewant/kefu_save.html
M	templates/freewant/order_showact.html
A	templates/freewant/poll_views.html
M	templates/freewant/shop_active.html
M	templates/freewant/shop_adv.html
M	templates/freewant/shop_comment.html
M	templates/freewant/shop_goods.html
M	templates/freewant/shop_index.html
M	templates/freewant/shop_menu.html
M	templates/freewant/shop_news.html
M	templates/freewant/shopcomment.html
M	templates/freewant/shopinfo.html
D	templates/freewant/shopping2-0822.html
D	templates/freewant/shoppingop0811.html
"""
]

result = vcseedftp.diff_ignore_filter( sample_output[0] )

print( result )
